# Generated by Django 2.2.24 on 2022-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='image_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
