# Generated by Django 2.2.24 on 2022-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paragraphs', '0003_auto_20220331_1110'),
        ('categories', '0001_initial'),
        ('favorites', '0002_auto_20220331_1110'),
        ('news', '0003_auto_20220122_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
