# Generated by Django 2.2.24 on 2022-01-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(max_length=100)),
                ('new', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body', to='news.New')),
            ],
        ),
    ]
