# Generated by Django 2.2.24 on 2022-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paragraphs', '0002_auto_20220122_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='new',
            new_name='news',
        ),
    ]
